<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>fake fetch data</title>
</head>
<body>
    <p id="output"></p>

    <script>
        const output = document.querySelector('#output');
        const fakeFetch = (url) => {
	return new Promise((resolve, reject) => {
	  setTimeout(() => {
	    if (url === "https://example.com/api/data") {
	      reject({
	        status: 500,
	        message: "Internal Server Error"
	      });
	    } else {
	      resolve({
	        status: 200,
	        data: {
	          message: "Success"
	        }
	      });
	    }
	  }, 2000);
	});
};

// Your Code here


fakeFetch("https://example.com/api/data")
.then((res) => console.log(res))
.catch((err) => {
    output.innerHTML = err.message;
})

// Output on the DOM should be: 
// Internal Server Error! The server crashed. Please try again in some time.
    </script>
</body>
</html>